---
- name: 'Ensure that the docker daemon is functional'
  docker_ping:
  retries: 5
  delay: 10
  until: result|success
  tags:
    - yujin-dockers

- name: Check we are logged into Docker Hub
  docker_login:
    username: "{{ yujin_dockerhub_user }}"
    password: "{{ yujin_dockerhub_password }}"
    email: "{{ yujin_dockerhub_email }}"
  tags:
    - yujin-dockers

- name: Ensure docker image has the proper version
  docker_image:
    name: "{{ item.name }}"
    tag: "{{ item.tag }}"
    force: "{{ item.force }}"
  with_items: "{{ yujin_docker_images }}"
  register: docker_images_updated
  tags:
    - yujin-dockers

- name: Ensure yujin dockers restarted
  become: yes
  supervisorctl:
   name: "{{ item.1.supervisor_program_id }}" # we get the program id from supervisor_program (only one)
   state: restarted
  when: "{{ item.0.changed and item.1.supervisor_program_id is defined }}"  # only the program that change
  with_nested:
  - "{{ docker_images_updated.results }}"
  - "{{ yujin_docker_images }}"
  tags:
    - yujin-dockers
