---
# Requirements too high for trusty (pexpect > 3.3)
#- name: "Calling groot_binaries"
#  expect:
#    command: "groot_binaries --{{ groot_distro }} {{ '--external' if groot_use_external else '' }}"
#    responses:
#      (?i)password: "{{ groot_password }}"

# direct groot binary call
- name: "Calling groot_binaries"
  command: "groot_binaries --{{ groot_stream|default(stable) }} {{ '--external' if groot_use_external|default(True) else '' }}"
  become: yes # we want to always use root here

# fixing https://github.com/yujinrobot/yujin_tools/issues/93
- name: "Fixing permissions in groot_binaries structure"
  file:
    path: "{{ item }}"
    state: directory
    mode: "g+rx,o+rx"
  become: yes
  with_items:
  - /opt/yujin/amd64/indigo-devel/share
  - /opt/yujin/amd64/indigo-devel/lib

#- name: "Installing groot_binaries dependencies"
#  command: "groot_binaries --{{ groot_stream|default(stable) }} --install-rosdeps"
#  when: "{{ groot_install_rosdeps|default(True) }}"
#

# Currently broken (Ansible 2.1.0.0)
#- name: synchronize binaries from internal files.yujinrobot.yujin.com server
#  become: yes
#  synchronize:
#    links: yes
#    recursive: yes
#    delete: yes
#    src: "files@files.yujinrobot.yujin.com:shared/installspaces/yujinrobot.yujin/amd64/indigo-{{ groot_stream }}"
#    dest: /opt/yujinrobot.yujin/amd64
#    mode: pull
#  delegate_to: "{{ inventory_hostname }}"
#  when: not groot_use_external
#
#- name: synchronize binaries from external files.yujinrobot.com server
#  become: yes
#  synchronize:
#    links: yes
#    recursive: yes
#    delete: yes
#    src: /opt/yujinrobot.yujin/amd64
#    dest: "/data/file_server/rsync_repositories/yujinrobot.yujin/amd64/indigo-{{ groot_stream }}"
#    mode: pull  # has to be push because of user permissions (ansible versus rsync/ssh settings)
#  delegate_to: "{{ inventory_hostname }}"
#  when: groot_use_external


- name: rosdep init
  command: "rosdep init"
  args:
    creates: /etc/ros/rosdep/sources.list.d/20-default.list
  become: yes
  changed_when: false  # we can probably ignore this, since changes would come from a change in previous task

- name: rosdep update
  command: "rosdep update"
  changed_when: false  # we can probably ignore this, since changes would come from a change in previous task

- name: rosdep install
  shell: "source /opt/yujin/amd64/indigo-{{ groot_stream }}/setup.bash && rosdep install -r --default-yes --from-paths /opt/yujin/amd64/indigo-{{ groot_stream }} --ignore-src"
  args:
     executable: /bin/bash
  changed_when: false  # we can probably ignore this, since changes would come from a change in previous task