---
 - name: 'Ensure that the docker daemon is functional'
   become: yes
   docker_ping:
   retries: 5
   delay: 10
   until: result|success

 - name: Check we are logged into Docker Hub
   docker_login:
     username: "{{ balcony_dockerhub_user }}"
     password: "{{ balcony_dockerhub_password }}"
     email: "{{ balcony_dockerhub_email }}"

 - name: Ensure balcony is latest
   docker_image:
     name: yujinrobot/balcony
     tag: latest

 - name : Ensure balcony is started
   supervisorctl:
     name: balcony-docker
     state: present
   tags: [balcony-docker]