- hosts: 
   - gocart-server
   - gocart-servertest
   - zach
  #strategy: debug
  pre_tasks:
   - name: 'Ensure that we can connect to this host'
     ping:

  roles:
   - role: geerlingguy.ntp
     tags: ntp
     become: yes
     ntp_enabled: true
     ntp_timezone: Etc/UTC
     ntp_manage_config: true
     ntp_servers: 
      -  0.ubuntu.pool.ntp.org iburst,
      -  1.ubuntu.pool.ntp.org iburst,
      -  2.ubuntu.pool.ntp.org iburst,
      -  3.ubuntu.pool.ntp.org iburst,
      -  ntp.ubuntu.com

  tasks:
  # TODO : this relies on yujin package -> also need to set that up
  # This task probably requires better user / ssh keys management.
   - cron:
       name: "Get groot_binaries"
       user: root
       hour: "17"  # this is 2AM Seoul Time
       # echo until we solve the automated authentication problem.
       job: "/usr/local/bin/groot_binaries --devel --external"
     become: yes