- name:  ANSIBLE - Clock Sync
  hosts:
   - concert
   - gocarts

  #strategy: debug
  pre_tasks:
   - name: 'Ensure that we can connect to this host'
     ping:

  roles:
   - role: geerlingguy.ntp
     become: yes
     tags: ntp
     ntp_enabled: true
     ntp_timezone: Etc/UTC
     ntp_manage_config: true
     ntp_servers: 
      -  0.ubuntu.pool.ntp.org iburst,
      -  1.ubuntu.pool.ntp.org iburst,
      -  2.ubuntu.pool.ntp.org iburst,
      -  3.ubuntu.pool.ntp.org iburst,
      -  ntp.ubuntu.com
     when: "'concert' in group_names"

   - role: asmodehn.chrony
     tags: chrony
     chrony_server:
       - concert minpoll 0 maxpoll 5 maxdelay .05
     when: "'gocarts' in group_names"
