- name:  ANSIBLE - Concert Master Playbook
  hosts:
   - concert

- include: clocksync.yml
- include: syncthing_gopher.yml
- include: groot_concert.yml
- include: balcony_docker.yml
- include: concert_portal.yml




