- hosts: 
   - gocart-server
   - gocart-servertest
  strategy: debug
  tasks:
    - name: 'Ensure that we can connect to this host'
      ping:
  roles:
   - role: geerlingguy.ntp
     tags: ntp
     become: yes
     ntp_enabled: true
     ntp_timezone: Etc/UTC
     ntp_manage_config: true
     ntp_servers: 
      -  0.ubuntu.pool.ntp.org iburst,
      -  1.ubuntu.pool.ntp.org iburst,
      -  2.ubuntu.pool.ntp.org iburst,
      -  3.ubuntu.pool.ntp.org iburst,
      -  ntp.ubuntu.com
   #- balcony
   #- ros_concert
   - role: syncthing
     tags: syncthing
     become: yes
     syncthing_version: 0.13.9
   - role: docker-role
     tags: docker
     become: yes
  tasks:
    - name: 'Ensure that the docker daemon is functional'
      become: yes
      docker_ping:
      retries: 5
      delay: 10
      until: result|success
    - name: 'docker selftest : hello world'
      docker:
        name: 'helloworld'
        image: 'hello-world'
        state: 'started'
