#
# Playbook to install baclony docker, preconfigured for gopher usage.
#
- hosts:
   - gocart-server
   - gocart-servertest
   - zach
  #strategy: debug
  pre_tasks:
   - name: 'Ensure that we can connect to this host'
     ping:

  vars_prompt:
   - name: "docker_hub_login"
     prompt: "Docker Hub Username"
     private: no
     tags: balcony-docker
   - name: "docker_hub_password"
     prompt: "Docker Hub password"
     private: yes
     tags: balcony-docker
   - name: "docker_hub_email"
     prompt: "Docker Hub email"
     private: no
     tags: balcony-docker

  roles:

   - role: balcony-docker
     tags: balcony-docker
     balcony_dockerhub_user: "{{ docker_hub_login }}"
     balcony_dockerhub_password: "{{ docker_hub_password }}"
     balcony_dockerhub_email: "{{ docker_hub_email }}"
     become: yes

   - role: tersmitten.supervisor
     become: yes
     supervisor_programs_present:
       balcony-docker:
         user: yujin
         command: docker run -i --net=\"host\" yujinrobot/balcony
         autostart: true
         stdout_logfile: /var/log/supervisor/balcony.out.log
         stderr_logfile: /var/log/supervisor/balcony.err.log

  post_tasks:
    - name: start balcony-docker service via supervisor
      become: yes
      supervisorctl:
        name: balcony-docker
        state: restarted
      tags:
        - balcony-docker-start