#
# Playbook to ensure gateway is isntalled, configured and running as expected
#
---
- name: ANSIBLE - Gateway
  hosts:
    - concert

  vars:
  - yujin_stream: devel
  - gateway_conf_directory: /opt/groot/gateway
  - flower_public_hostname: concert  # TODO : should be {{ inventory_hostname }}
  - scheduler_public_hostname: concert  # TODO : should be {{ inventory_hostname }}
  - rostful_public_hostname: concert  # TODO : should be {{ inventory_hostname }}
  - reporter_public_hostname: concert  # TODO : should be {{ inventory_hostname }}

  vars_prompt:
   - name: "docker_hub_login"
     prompt: "Docker Hub Username"
     private: no
     tags: gateway-docker
   - name: "docker_hub_password"
     prompt: "Docker Hub password"
     private: yes
     tags: gateway-docker
   - name: "docker_hub_email"
     prompt: "Docker Hub email"
     private: no
     tags: gateway-docker

  pre_tasks:
  - name: 'Ensure that we can connect to this host'
    ping:

# ansible-galaxy is not idempotent yet, and we cannot force update, so let the user do it manually
#   - name: 'Ensure we have galaxy dependencies installed'
#     local_action: command ansible-galaxy install -r requirements.yml -p roles

  roles:

  # TODO : do a specific gateway role since we need template config file.
  - role: yujinrobot.gateway-docker
    tags: gateway-docker
    gateway_dockerhub_user: "{{ docker_hub_login }}"
    gateway_dockerhub_password: "{{ docker_hub_password }}"
    gateway_dockerhub_email: "{{ docker_hub_email }}"
    gateway_docker_image_tag: "{{ yujin_stream }}"
    gateway_docker_image_force: yes
    gateway_docker_conf_volume_path: "{{ gateway_conf_directory }}"

  - role: asmodehn.supervisor
    supervisor_version: apt
    tags: gateway-docker
    become: yes
    supervisor_programs_present:
      gateway-docker:
        user: yujin
        command: docker run -i --net=\"host\" -v "{{ gateway_conf_directory }}:/app/config/userConfig" "yujinrobot/rocon_api_gateway:{{ yujin_stream }}"
        stopasgroup: true
        stopwaitsecs: 2
        killasgroup: true
        autostart: true
        stdout_logfile: "/var/log/supervisor/gateway-docker.out.log"
        stderr_logfile: "/var/log/supervisor/gateway-docker.err.log"

  post_tasks:

    # TODO : restart only if image or configuration changed
    - name: Supervisorctl restart
      become: yes
      shell: "supervisorctl restart gateway-docker"
      # supervisorctl ansible module is buggy. using shell command instead.
