 - src: geerlingguy.ntp

 - src: tersmitten.supervisor

 - src: marvinpinto.docker


 - src: https://github.com/asmodehn/ansible-syncthing-debian.git
   version: master
   name: asmodehn.syncthing


 - src: https://github.com/asmodehn/ansible-role-ros.git
   version: master
   name: asmodehn.ros
