#
# Playbook to install ROS gopher software.
#
- hosts:
   - gocart201
   - gocart202
   - gocart203
   - gocart204

  #strategy: debug
  pre_tasks:
   - name: 'Ensure that we can connect to this host'
     ping:

  roles:

  post_tasks:
    - name: start syncthing service via supervisor
      become: yes
      supervisorctl:
        name: syncthing
        state: restarted
      tags:
        - syncthing-start