#
# Playbook to install ROS concert software.
#
- hosts:
   - gocart-server
   - gocart-servertest
   - zach

  #strategy: debug
  pre_tasks:
   - name: 'Ensure that we can connect to this host'
     ping:

  roles:
   - role: groot
     become: yes
     groot_distro: devel
     groot_password: "{{ vault_groot_password }}"

#  post_tasks:
#   - name: start syncthing service via supervisor
#     become: yes
#     supervisorctl:
#       name: syncthing
#       state: restarted
#     tags:
#       - syncthing-start