galaxy_info:
  author: AlexV
  description: Role to install yujinrobot.yujin packages
  company: YujinRobot
  license: BSD
  min_ansible_version: 1.2

  platforms:
  - name: Ubuntu
    versions:
    - trusty

dependencies:
  - role: asmodehn.ros
    become: yes
    ros_release: "indigo"
    ros_package: "ros-base"
    ros_apt_uri: "http://packages.ros.org/ros/ubuntu"
    ros_apt_key: "https://raw.githubusercontent.com/ros/rosdistro/master/ros.key"
